/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "news.index": [],
    "news.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "dashboard": [],
    "admin.categories.index": [],
    "admin.categories.create": [],
    "admin.categories.store": [],
    "admin.categories.show": [
        {
            "name": "category",
            "required": true
        }
    ],
    "admin.categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.index": [],
    "admin.posts.create": [],
    "admin.posts.store": [],
    "admin.posts.show": [
        {
            "name": "post",
            "required": true
        }
    ],
    "admin.posts.edit": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.update": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.destroy": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.doctors.index": [],
    "admin.doctors.create": [],
    "admin.doctors.store": [],
    "admin.doctors.show": [
        {
            "name": "doctor",
            "required": true
        }
    ],
    "admin.doctors.edit": [
        {
            "name": "doctor",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.doctors.update": [
        {
            "name": "doctor",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.doctors.destroy": [
        {
            "name": "doctor",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.themes.index": [],
    "admin.themes.create": [],
    "admin.themes.store": [],
    "admin.themes.show": [
        {
            "name": "theme",
            "required": true
        }
    ],
    "admin.themes.edit": [
        {
            "name": "theme",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.themes.update": [
        {
            "name": "theme",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.themes.destroy": [
        {
            "name": "theme",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.intro-pages.index": [],
    "admin.intro-pages.create": [],
    "admin.intro-pages.store": [],
    "admin.intro-pages.show": [
        {
            "name": "intro_page",
            "required": true
        }
    ],
    "admin.intro-pages.edit": [
        {
            "name": "intro_page",
            "required": true
        }
    ],
    "admin.intro-pages.update": [
        {
            "name": "intro_page",
            "required": true
        }
    ],
    "admin.intro-pages.destroy": [
        {
            "name": "intro_page",
            "required": true
        }
    ],
    "admin.popups.index": [],
    "admin.popups.create": [],
    "admin.popups.store": [],
    "admin.popups.show": [
        {
            "name": "popup",
            "required": true
        }
    ],
    "admin.popups.edit": [
        {
            "name": "popup",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.popups.update": [
        {
            "name": "popup",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.popups.destroy": [
        {
            "name": "popup",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sitemap-categories.index": [],
    "admin.sitemap-categories.create": [],
    "admin.sitemap-categories.store": [],
    "admin.sitemap-categories.show": [
        {
            "name": "sitemap_category",
            "required": true
        }
    ],
    "admin.sitemap-categories.edit": [
        {
            "name": "sitemap_category",
            "required": true
        }
    ],
    "admin.sitemap-categories.update": [
        {
            "name": "sitemap_category",
            "required": true
        }
    ],
    "admin.sitemap-categories.destroy": [
        {
            "name": "sitemap_category",
            "required": true
        }
    ],
    "admin.sitemaps.index": [],
    "admin.sitemaps.create": [],
    "admin.sitemaps.store": [],
    "admin.sitemaps.show": [
        {
            "name": "sitemap",
            "required": true
        }
    ],
    "admin.sitemaps.edit": [
        {
            "name": "sitemap",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sitemaps.update": [
        {
            "name": "sitemap",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sitemaps.destroy": [
        {
            "name": "sitemap",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.translate": [],
    "doctors.index": [],
    "search.suggest": [],
    "hospital.info": [],
    "services": [],
    "departments": [],
    "research": [],
    "facilities": [],
    "donation": [],
    "careers": [],
    "procurement": [],
    "suggestions": [],
    "pr": [],
    "map": [],
    "sitemap": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
